# Add your code below
version: '3.1'

services:
  mongodb:
    container_name: hyper-mongo
    image: mongo:6.0.8
    restart: always
    ports:
      - '27027:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - hyper-task-manager-network
    volumes:
      - mongo-data:/data/db

  hyper-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyper-task-manager
    restart: always
    ports:
      - '8000:8000'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    networks:
      - hyper-task-manager-network
    depends_on:
      - mongodb

networks:
  hyper-task-manager-network:

volumes:
  mongo-data:
